[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
target = "./target"

[programs.localnet]
programs = "4oVhv3o16X3XR99UgbFrWNKptoNBkg2hsbNY2nYPpv4a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./localnet-keys/admin.json"

[scripts]
test = "echo 'use bun run test instead' && exit 1"
